### ISSUE TITLE
내 프로필 페이지 + github rest api 깃헙 이슈 생성용 문의 컴포넌트 적용

### ISSUE THREAD

**Issue by tooget** [tooget/tooget.github.io#3]
## 이런 목표를 달성해야 합니다
> 이 이슈로 무슨 목표를 달성하고자 하며 어떤 상태가 되어야 하는지 간결히 적어주세요.

NUXT 내 프로필 페이지 초기 구성 및 staticman.net 를 이용한 소통 채널을 구현합니다.

## 현재 이런 상태입니다
> 이 이슈를 생성한 현시점의 문제 혹은 향후 문제 발생 가능성에 대하여 간결히 적어주세요.

https://github.com/tooget/tooget.github.io/commit/bfc58f86c340d751ec93809ddaa1667f46e7b019 기준, create-nuxt-app 기본 페이지만 존재합니다.

## 이 이슈는 이 분이 풀 수 있을 것 같습니다
> 담당할 Assignee를 @로 **1명만** 멘션해주세요.

@tooget 

## 아래의 세부적인 문제를 풀어야 할 것 같습니다
> 이 이슈를 해결하기 위한 세부 항목(이슈 클로징 조건)을 체크리스트로 적어주세요.
  - [x] https://linkedin.com/in/tooget 등 개인 프로필 컴포넌트 임베딩
  - [x] 간단한 이력 컴포넌트 추가
  - [ ] ~~https://staticman.net~~ git rest api +입력 폼 컴포넌트 추가

## 이 이슈를 해결하기 위해 이런 내용을 참고할 수 있을 것 같습니다
> 문제 해결에 도움이 될 수 있을 것 같은 관련 이슈 번호, 문서, Wiki, 스크린샷, 개인적인 의견 등을 최대한 적어주세요.
> 이 이슈가 다른 이슈와 관련되어 있는 경우는 **반드시 이슈 번호를 적어주세요**
  - 관련이슈: #1 
  - 참고사항
    - https://staticman.net
    - https://mebee.info/2020/02/13/post-6102/
    - https://bestofvue.com/tag/timeline-maker

## 이 이슈 해결을 위해 이정도 시간이 예상됩니다
> 예상소요시간을 한가지만 선택해주세요.
> (1W+ 가 아닌 경우 레이블을 변경해주세요.)
  - 예상소요시간: **1W-**

## 관련된 세부 정보입니다.
> Reporter는 **1명만**, Domain, Priority, Task를 **각각 한가지만** 선택해주세요.
> (UX, Medium, Enhancement 가 아닌 경우 레이블을 변경해주세요.)
  - Reporter: @tooget 
  - Domain  : **UX**
  - Priority: **High**
  - Task    : **Enhancement**

## 이 이슈를 해결함에 따라 이정도 재무적 영향이 예상됩니다.
> 이 이슈를 해결함에 따라 전사적으로 유의미한 수익/비용 변동이 예상될 경우, 해당 수치를 입력해주세요.
  - 예상수익: 0 원/월
  - 예상비용: 0 원/월

**Comment by tooget** [comment]
## https://staticman.net 사용 보류
 - heroku로 백엔드 서버를 생성하는 구성인 듯
 - 인프라를 별도 생성하지 않고 간결한 인프라(Github 만으로 구성)를 유지할 예정이므로, 사용 보류

## 대안: Github Graphql API v4 사용 보류
 - 레퍼런스: https://docs.github.com/en/graphql/guides/forming-calls-with-graphql#the-graphql-endpoint
 - 테스트: https://lucasconstantino.github.io/graphiql-online/ ← `https://api.github.com/graphql`
 - 문제점: 인증 필수
```json
{
  "message": "This endpoint requires you to be authenticated.",
  "documentation_url": "https://docs.github.com/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql"
}
```

## 대안: Github REST API v3 로 직접 사용
 - https://docs.github.com/ja/rest/guides/getting-started-with-the-rest-api
    - https://docs.github.com/ja/rest/reference/issues#list-repository-issues

**Comment by tooget** [comment]
@T-Mook NUXT 알려주세요! ~~프런트엔드는 잘 모르겠습니다..~~

`asyncData`로 `listedJsonIssuesInfo`를 렌더링하려고 하는데 에러가 뜹니다
```vue
<template>
  <v-simple-table>
    <template #default>
      <thead>
        <tr>
          <th class="text-left">IssueNumber</th>
          <th class="text-left">Title</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="item in listedJsonIssuesInfo" :key="item.id">
          <td>{{ item.number }}</td>
          <td>
            <a href="item.url" target="_blank" rel="noopener noreferrer">{{
              item.title
            }}</a>
          </td>
        </tr>
      </tbody>
    </template>
  </v-simple-table>
</template>


<script>
export default {
  async asyncData({ $axios }) {
    const listedJsonIssuesInfo = await $axios.$get(
      'https://api.github.com/repos/tooget/tooget.github.io/issues?state=all'
    )
    console.log(listedJsonIssuesInfo)
    return { listedJsonIssuesInfo }
  },
}
</script>
```
```
[Vue warn]: Property or method "listedJsonIssuesInfo" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
```
`mount` `fetch` 랑 사용을 구분하라는 등등 여러가지 적혀있는데.. 결국 `asyncData`로 에러가 안나게 하려면 어떻게 해야 하나요??

**Comment by T-Mook** [comment]
@tooget `asyncData` 쪽 코드가 문제인 것 같지는 않아 보이는데...
아래처럼 해봐도 될까요

```javascript
export default {
  async asyncData({ $axios }) {
    try { // <---- (1) 혹시 모르니 try, catch 추가
      const listedJsonIssuesInfo = await $axios.$get(
        'https://api.github.com/repos/tooget/tooget.github.io/issues?state=all'
      )
      console.log(listedJsonIssuesInfo)
      return { listedJsonIssuesInfo }
    } catch(err) {
      console.log(err) // <---- (2) 혹시 모르니 try, catch 추가
    }
  },
  /* (3) 이 아래 추가 */
  data() {
    return { 
      listedJsonIssuesInfo: [],
    }
  },
}
```

**Comment by tooget** [comment]
@T-Mook 
https://github.com/tooget/tooget.github.io/issues/3#issuecomment-907567331 내용 반영한 뒤 에러 안뜨고 데이터도 안나오네요..
![Screen Shot 2021-08-28 at 14 00 43](https://user-images.githubusercontent.com/24958726/131206767-593f5967-79c3-464b-af3e-dd40e0e1418f.png)
`data()`가 공백인 상태가 표현되어서 `asyncData` 가 호출한 데이터가 반영이 안되는 걸까요..?

**Comment by T-Mook** [comment]
@tooget 
순서상 저 빈 `listedJsonIssuesInfo`을 `asyncData` 결과가 대치할 거라 그렇진 않을 텐데...흠
1. `'https://api.github.com/repos/tooget/tooget.github.io/issues?state=all'` 이거 통신 결과 제대로 오고 있는 거겠죠?
   *  $axios의 정상동작이 궁금한 것
   * 제가 그냥 url 찍어봤을 땐 결과는 잘 보이긴 하는데..
1. 또는 위 문제가 아니라면 `listedJsonIssuesInfo`를 화면에 그냥 무식하게 `{{ String(listedJsonIssuesInfo) }}` 했을 때 보이나요?

**Comment by tooget** [comment]
@T-Mook 님, `create-nuxt-app` 자체를 새로 초기화했는데도 `axios` 모듈이 동작하지 않는 것 같습니다. ~~정상작동하지 않는데 왜 동작 안하는 지 아무리 찾아도 이해할 수 없다???~~
혹시 내일 이 부분 관련하여 기초적인 nuxt - axios 구조에 대한 가르쳐 주실 수 있으실까요! 시간 괜찮으신가요!

**Comment by T-Mook** [comment]
@tooget 

제가 구조를 알고 있는건 없다고 봐도 되지만 이 상황에 대해서 낼 같이 고민해봐요 ㅋㅋ

**Comment by tooget** [comment]
@T-Mook 
To join the video meeting, click this link: https://meet.google.com/rps-qzqj-hnd

**Comment by T-Mook** [comment]
@tooget 
* https://nuxtjs.org/docs/2.x/features/data-fetching
> The asyncData hook. This hook can only be placed on page components. Unlike fetch, this hook does not display a loading placeholder during client-side rendering: instead, this hook blocks route navigation until it is resolved, displaying a page error if it fails.

**Comment by tooget** [comment]
> **This hook can only be placed on page components.**

!!!!

**Comment by T-Mook** [comment]
* 부모에서 자녀한테 상속하는 법
## 부모 컴포넌트
```html
<content-card-btns
            :top-contents="contentsName"
/>
```
```javascript
export default {
   data() {
     return {
       contentsName: 'something',
    }
}
```
## 자녀 컴포넌트
```javascript
export default {
   props: {
       topContents: { type: Boolean, default: false },
   },
  data() {
    return {
      anything : this.topContents // 이렇게 써도 되 고 직접 this.topContents로 써도 됨
    }
}
```

* https://day0404.tistory.com/13

@tooget

**Comment by tooget** [comment]
## NUXT 잘 모르는 점
 - Colon(:) 및 중괄호({{ }}) 의 차이, 콜론을 사용하게 한 이유?
 - 부모 컴포넌트의 `top-contents` 변수가 → 자식 컴포넌트 `props` 변수 `topContents`를 대응시킨 이유?
   - `props` 사용에 따른 cammel case - kebab case의 사용에 대한 NUXT 공식문서: https://kr.vuejs.org/v2/guide/components-props.html#Prop-%EB%8C%80%EC%86%8C%EB%AC%B8%EC%9E%90-%EA%B5%AC%EB%B6%84-camelCase-vs-kebab-case
   - 참고: https://michaelnthiessen.com/vue-props-ultimate-guide

**Comment by tooget** [comment]
## Github API Oauth App 참고
 - https://aristath.github.io/blog/static-site-comments-using-github-issues-api

**Comment by tooget** [comment]
## API 구현은 별도 이슈로 분리 https://github.com/tooget/tooget.github.io/issues/4
 - 사유: 변경 파일 및 커밋 내용이 많아짐
    - self-recommend: 10개 파일, 10개 커밋 이내
